name: Python Testing

permissions:
  contents: read

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
      - name: Run coverage with unittest
        run: |
          coverage run -m unittest
          coverage report --skip-empty --fail-under=80 --precision=1
